[versions]
android_gradle_plugin = "8.13.2"
kotlin_gradle_plugin = "2.3.0"
ksp_gradle_plugin = "2.3.5"
coreKtx = "1.17.0"
compileSdk = "36"
minSdk = "26"
targetSdk = "35"
appcompat = "1.7.1"
material = "1.13.0"
junit = "4.13.2"
room = "2.8.4"
robolectric = "4.16"
testCore = "1.7.0"
testExtJunit = "1.3.0"
testRunner = "1.7.0"
testRules = "1.7.0"
espresso = "3.7.0"
turbine = "1.2.1"
retrofit = "3.0.0"
okhttp = "5.3.2"
moshi = "1.15.2"
androidx_annotation = "1.9.1"
mockk = "1.14.7"
kotlinx_coroutines_test = "1.10.2"
kotlin_test_junit = "2.3.0"
androidx-compose-bom = "2025.12.01"
androidx-navigation-compose = "2.9.6"
androidx-compose-material-icons-extended = "1.7.8"
androidx-compose-ui = "1.10.0"
androidx-compose-material3 = "1.4.0"
androidx-activity-compose = "1.12.2"
hilt = "2.57.2"
hilt_navigation_compose = "1.3.0"
androidx_core_splashscreen = "1.2.0"
composeAnimation = "1.10.0"
dropshots = "0.5.1"
genai_prompt = "1.0.0-beta1"

[libraries]
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx_core_splashscreen" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
com-google-android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "testCore" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "testRunner" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "testRules" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "testExtJunit" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
cash-turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
okhttp-mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidx_annotation" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx_coroutines_test" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin_test_junit" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation-compose" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "androidx-compose-material-icons-extended" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "androidx-compose-ui" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidx-compose-material3" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "composeAnimation" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "androidx-compose-ui" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "androidx-compose-ui" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt_navigation_compose" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
google-mlkit-genai-prompt = { group = "com.google.mlkit", name = "genai-prompt", version.ref = "genai_prompt" }


[plugins]
android-application = { id = "com.android.application", version.ref = "android_gradle_plugin" }
android-library = { id = "com.android.library", version.ref = "android_gradle_plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin_gradle_plugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp_gradle_plugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin_gradle_plugin" }
dropshots = { id = "com.dropbox.dropshots", version.ref = "dropshots" }